### ISSUE TITLE
Throws exception on GCP Linux VM

### ISSUE THREAD

**Issue by vishalgoswami** [GoogleCloudPlatform/keyrotator#13]
I tried to use keyrotator on GCP instance 
Linux 3.10.0-957.5.1.el7.x86_64 #1 SMP Fri Feb 1 14:54:57 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

I used the steps mentioned in the help as follows
1. git clone https://github.com/GoogleCloudPlatform/keyrotator.git
2. python setup.py install
  File "setup.py", line 47, in <module>
    "console_scripts": ["keyrotator = keyrotator.keyrotator:main"]
  File "/usr/lib64/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/site-packages/setuptools/command/install.py", line 73, in run
    self.do_egg_install()
  File "/usr/lib/python2.7/site-packages/setuptools/command/install.py", line 101, in do_egg_install
    cmd.run()
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 380, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 604, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 655, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 706, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 618, in resolve
    dist = best[req.key] = env.best_match(req, self, installer)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 862, in best_match
    return self.obtain(req, installer) # try and download/install
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 874, in obtain
    return installer(requirement)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 623, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 653, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 849, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1130, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1115, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 69, in run_setup
    lambda: execfile(
  File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 120, in run
    return func()
  File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 71, in <lambda>
    {'__file__':setup_script, '__name__':'__main__'}
  File "setup.py", line 88, in <module>
    
  File "/usr/lib64/python2.7/distutils/core.py", line 112, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 269, in __init__
    _Distribution.__init__(self,attrs)
  File "/usr/lib64/python2.7/distutils/dist.py", line 287, in __init__
    self.finalize_options()
  File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 302, in finalize_options
    ep.load()(self, ep.name, value)
  File "build/bdist.linux-x86_64/egg/setuptools_scm/integration.py", line 10, in version_keyword
  File "build/bdist.linux-x86_64/egg/setuptools_scm/version.py", line 66, in _warn_if_setuptools_outdated
**setuptools_scm.version.SetuptoolsOutdatedWarning: your setuptools is too old (<12)**

3. keyrotator
Traceback (most recent call last):
  File "/bin/keyrotator", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 3007, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 728, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 626, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: python-dateutil

Any idea why it doesnt work ?

**Comment by hshin-g** [comment]
@vishalgoswami Can you try running `pip install --upgrade setuptools pip` to upgrade setuptools and pip and try running again?

**Comment by vishalgoswami** [comment]
Thanks @hshin-g 
upgraded the pip and setuptools now. Now I have a different error when i install keyrotator

[root@util-vm keyrotator]#  python setup.py install
running install
running bdist_egg
running egg_info
writing requirements to keyrotator.egg-info/requires.txt
writing keyrotator.egg-info/PKG-INFO
writing top-level names to keyrotator.egg-info/top_level.txt
writing dependency_links to keyrotator.egg-info/dependency_links.txt
writing entry points to keyrotator.egg-info/entry_points.txt
reading manifest file 'keyrotator.egg-info/SOURCES.txt'
writing manifest file 'keyrotator.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/keyrotator
copying build/lib/keyrotator/__init__.py -> build/bdist.linux-x86_64/egg/keyrotator
copying build/lib/keyrotator/cleanup.py -> build/bdist.linux-x86_64/egg/keyrotator
copying build/lib/keyrotator/create.py -> build/bdist.linux-x86_64/egg/keyrotator
copying build/lib/keyrotator/delete.py -> build/bdist.linux-x86_64/egg/keyrotator
copying build/lib/keyrotator/iam_service.py -> build/bdist.linux-x86_64/egg/keyrotator
copying build/lib/keyrotator/keyrotator.py -> build/bdist.linux-x86_64/egg/keyrotator
copying build/lib/keyrotator/list.py -> build/bdist.linux-x86_64/egg/keyrotator
copying build/lib/keyrotator/version.py -> build/bdist.linux-x86_64/egg/keyrotator
byte-compiling build/bdist.linux-x86_64/egg/keyrotator/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/keyrotator/cleanup.py to cleanup.pyc
byte-compiling build/bdist.linux-x86_64/egg/keyrotator/create.py to create.pyc
byte-compiling build/bdist.linux-x86_64/egg/keyrotator/delete.py to delete.pyc
byte-compiling build/bdist.linux-x86_64/egg/keyrotator/iam_service.py to iam_service.pyc
byte-compiling build/bdist.linux-x86_64/egg/keyrotator/keyrotator.py to keyrotator.pyc
byte-compiling build/bdist.linux-x86_64/egg/keyrotator/list.py to list.pyc
byte-compiling build/bdist.linux-x86_64/egg/keyrotator/version.py to version.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying keyrotator.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying keyrotator.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying keyrotator.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying keyrotator.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying keyrotator.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying keyrotator.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/keyrotator-0.0.2-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing keyrotator-0.0.2-py2.7.egg
Copying keyrotator-0.0.2-py2.7.egg to /usr/lib/python2.7/site-packages
Adding keyrotator 0.0.2 to easy-install.pth file
Installing keyrotator script to /usr/bin
Installed /usr/lib/python2.7/site-packages/keyrotator-0.0.2-py2.7.egg
Processing dependencies for keyrotator==0.0.2
**error:** pyasn1 0.1.9 is installed but pyasn1<0.5.0,>=0.4.1 is required by set(['pyasn1-modules'])

**Comment by vishalgoswami** [comment]
installed it now using
>pip install pyasn1-modules

When I run keyrotator, it throws following error
[root@util-vm keyrotator]# keyrotator
Traceback (most recent call last):
  File "/bin/keyrotator", line 11, in <module>
    load_entry_point('keyrotator==0.0.2', 'console_scripts', 'keyrotator')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build/bdist.linux-x86_64/egg/keyrotator/keyrotator.py", line 46, in <module>
  File "build/bdist.linux-x86_64/egg/keyrotator/cleanup.py", line 22, in <module>
  File "build/bdist.linux-x86_64/egg/keyrotator/delete.py", line 18, in <module>
  File "build/bdist.linux-x86_64/egg/keyrotator/iam_service.py", line 22, in <module>
ImportError: No module named oauth2client.client

**Comment by vishalgoswami** [comment]
Got it running now had to do following:
[root@util-vm keyrotator]# pip install --upgrade oauth2client
