### ISSUE TITLE
It doesnt work in python 3 version

### ISSUE THREAD

**Issue by tharasavio** [GoogleCloudPlatform/keyrotator#15]
It doesnt work in python 3 version.It throws the below error

Traceback (most recent call last):
  File "/usr/local/bin/keyrotator", line 11, in <module>
    load_entry_point('keyrotator==0.0.2', 'console_scripts', 'keyrotator')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/dist-packages/keyrotator-0.0.2-py3.6.egg/keyrotator/keyrotator.py", line 46, in <module>
ImportError: cannot import name 'CleanupCommand'

**Comment by ilcapone** [comment]
Same problem here

`Traceback (most recent call last):
  File "/usr/local/bin/keyrotator", line 11, in <module>
    load_entry_point('keyrotator==0.0.2', 'console_scripts', 'keyrotator')()
  File "/usr/local/lib/python3.6/dist-packages/setuptools-45.2.0-py3.6.egg/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.6/dist-packages/setuptools-45.2.0-py3.6.egg/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.6/dist-packages/setuptools-45.2.0-py3.6.egg/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/usr/local/lib/python3.6/dist-packages/setuptools-45.2.0-py3.6.egg/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/dist-packages/keyrotator-0.0.2-py3.6.egg/keyrotator/keyrotator.py", line 46, in <module>
ModuleNotFoundError: No module named 'cleanup'`

**Comment by Mistic92** [comment]
Any update for this?

**Comment by sharipalik** [comment]
@tharasavio @ilcapone Any updates for that?
